import clickhouse_connect
import csv


Query = """
    SELECT
	bill_payer_account_id,
	line_item_usage_account_id,
	resource_group,
	resource_type,
	usage_type,
	line_item_usage_type,
	line_item_product_code,
	line_item_availability_zone,
	line_item_resource_id,
	line_item_usage_amount,
	product_product_name,
	product_instance_type,
	product_vcpu,
	product_memory,
	product_operating_system,
	product_volume_api_name,
	product_instance_type,
	product_database_engine,
	product_deployment_option,
	oci_shape,
	sku_mysql_shape,
	sku_postgresql_shape,
	sku_oracle_shape,
	sku_sql_server_shape,
	oci_obj_storage_class,
	oci_est_price,
	resource_tags_user_application,
	resource_tags_user_application_name,
	resource_tags_user_application_team,
	resource_tags_user_b_u,
	resource_tags_user_billing,
	resource_tags_user_business_unit,
	resource_tags_user_business_unit_division,
	resource_tags_user_c_m_d_b_a_p_m_number,
	resource_tags_user_c_r,
	resource_tags_user_category,
	resource_tags_user_channel,
	resource_tags_user_cluster_id,
	resource_tags_user_cluster_name,
	resource_tags_user_content_repo,
	resource_tags_user_content_repo_name,
	resource_tags_user_cyera,
	resource_tags_user_dept,
	resource_tags_user_enviornment,
	resource_tags_user_environment,
	resource_tags_user_event,
	resource_tags_user_kubernetes_cluster,
	resource_tags_user_league,
	resource_tags_user_marquis,
	resource_tags_user_match_name,
	resource_tags_user_media_silo_cloud_front,
	resource_tags_user_media_silo_domain,
	resource_tags_user_migration,
	resource_tags_user_migration_origin,
	resource_tags_user_migration_wave,
	resource_tags_user_organization,
	resource_tags_user_partner,
	resource_tags_user_platform,
	resource_tags_user_program,
	resource_tags_user_project,
	resource_tags_user_propeller_channel,
	resource_tags_user_propeller_input_proxy,
	resource_tags_user_propeller_organization,
	resource_tags_user_purpose,
	resource_tags_user_resource_lease_end_date,
	resource_tags_user_retention,
	resource_tags_user_role,
	resource_tags_user_s3_appboy,
	resource_tags_user_schedule,
	resource_tags_user_service,
	resource_tags_user_services,
	resource_tags_user_sub_b_u_division,
	resource_tags_user_sub_business_unit,
	resource_tags_user_vendor,
	resource_tags_user_wave,
	resource_tags_user_zone,
	resource_tags_user_app,
	resource_tags_user_app_name,
	resource_tags_user_aws_application,
	resource_tags_user_brand,
	resource_tags_user_business,
	resource_tags_user_cbsnews_cost_center,
	resource_tags_user_cbsnews_unit_name,
	resource_tags_user_covid19,
	resource_tags_user_crossplane_paramount_tech_xr_name,
	resource_tags_user_env,
	resource_tags_user_group,
	resource_tags_user_k8s_io_cluster_autoscaler_node_template_label_k8s_viacbs_tech_gha_runners,
	resource_tags_user_k8s_io_cluster_autoscaler_node_template_label_k8s_viacbs_tech_nodepool,
	resource_tags_user_k8s_io_cluster_autoscaler_use1_application_dev,
	resource_tags_user_k8s_viacbs_tech_nodepool,
	resource_tags_user_kubernetes_io_cluster_use1_application_dev,
	resource_tags_user_mtvi_managed,
	resource_tags_user_mtvi_role,
	resource_tags_user_mtvi_sitename,
	resource_tags_user_mtvi_status,
	resource_tags_user_ops_application,
	resource_tags_user_ops_environment,
	resource_tags_user_ops_project,
	resource_tags_user_pluto_app_version,
	resource_tags_user_pluto_deploy_repo_name,
	resource_tags_user_pluto_deploy_repo_path,
	resource_tags_user_pluto_deploy_tf_state_loc,
	resource_tags_user_pluto_deploy_tool,
	resource_tags_user_pluto_dept,
	resource_tags_user_pluto_env_account_name,
	resource_tags_user_pluto_env_app,
	resource_tags_user_pluto_env_name,
	resource_tags_user_pluto_env_teir,
	resource_tags_user_pluto_env_tier,
	resource_tags_user_pluto_jira_epic,
	resource_tags_user_pluto_name,
	resource_tags_user_pluto_service_owner_business,
	resource_tags_user_pluto_department,
	resource_tags_user_plutoenv,
	resource_tags_user_snapshot_origin,
	resource_tags_user_tf,
	resource_tags_user_tf_build_info,
	resource_tags_user_tf_module,
	resource_tags_user_tf_org,
	resource_tags_user_tf_repo_name,
	resource_tags_user_tf_repo_org,
	resource_tags_user_version,
	oci_shape,
	resource_group,
	resource_type,
	usage_type,
	sku_ocpu_sku_id,
	sku_ocpu_unit_price,
	sku_ocpu_quantity,
	sku_ocpu_price,
	sku_memory_sku_id,
	sku_memory_unit_price,
	sku_memory_quantity,
	sku_memory_price,
	sku_boot_volume_sku_id,
	sku_boot_volume_unit_price,
	sku_boot_volume_quantity,
	sku_boot_volume_price,
	sku_gpu_sku_id,
	sku_gpu_unit_price,
	sku_gpu_quantity,
	sku_gpu_price,
	sku_os_sku_id,
	sku_os_unit_price,
	sku_os_quantity,
	sku_os_price,
	oci_est_price,
	sku_vm_data_transfer_unit_price,
	sku_vm_data_transfer_quantity,
	sku_vm_data_transfer_sku_id,
	sku_vm_data_transfer_price,
	sku_vol_perf_unit_price,
	sku_vol_perf_sku_id,
	sku_vol_price,
	sku_vol_sku_id,
	sku_vol_unit_price,
	sku_vol_perf_quantity,
	sku_vol_quantity,
	sku_vol_perf_price,
	sku_postgresql_storage_sku_id,
	sku_mysql_shape,
	sku_mysql_heatwave_unit_price,
	sku_sql_server_os_price,
	sku_oracle_storage_unit_price,
	sku_sql_server_ocpu_unit_price,
	sku_oracle_license_quantity,
	sku_sql_server_memory_price,
	sku_mysql_ecpu_price,
	sku_mysql_heatwave_sku_id,
	sku_sql_server_ocpu_sku_id,
	sku_sql_server_shape,
	sku_postgresql_memory_price,
	sku_oracle_shape,
	sku_sql_server_os_unit_price,
	sku_postgresql_ocpu_capacity_price,
	sku_oracle_ocpu_unit_price,
	sku_postgresql_memory_sku_id,
	sku_postgresql_memory_unit_price,
	sku_oracle_ocpu_sku_id,
	sku_mysql_storage_quantity,
	sku_sql_server_ocpu_quantity,
	sku_postgresql_storage_price,
	sku_oracle_license_price,
	sku_postgresql_shape,
	sku_sql_server_os_quantity,
	sku_sql_server_memory_unit_price,
	sku_mysql_ecpu_unit_price,
	sku_mysql_storage_sku_id,
	sku_mysql_ecpu_quantity,
	sku_mysql_storage_unit_price,
	sku_postgresql_ocpu_sku_id,
	sku_sql_server_os_sku_id,
	sku_mysql_storage_price,
	sku_oracle_storage_sku_id,
	sku_postgresql_ocpu_unit_price,
	sku_postgresql_ocpu_capacity_sku_id,
	sku_postgresql_ocpu_price,
	sku_oracle_license_unit_price,
	sku_oracle_storage_quantity,
	sku_mysql_ecpu_sku_id,
	sku_oracle_license_sku_id,
	sku_mysql_heatwave_price,
	sku_oracle_ocpu_quantity,
	sku_postgresql_ocpu_capacity_unit_price,
	sku_oracle_ocpu_price,
	sku_oracle_storage_price,
	sku_sql_server_memory_quantity,
	sku_sql_server_memory_sku_id,
	sku_postgresql_memory_quantity,
	sku_postgresql_ocpu_quantity,
	sku_postgresql_storage_unit_price,
	sku_postgresql_ocpu_capacity_quantity,
	sku_postgresql_storage_quantity,
	sku_sql_server_ocpu_price,
	sku_mysql_heatwave_quantity,
	sku_obj_storage_quantity,
	oci_obj_storage_class,
	sku_obj_data_retreival_quantity,
	sku_obj_data_retreival_unit_price,
	sku_obj_data_retreival_price,
	sku_obj_storage_unit_price,
	sku_obj_storage_price,
	sku_obj_data_retreival_sku_id,
	sku_obj_storage_sku_id,
	sku_service_sku_id,
	sku_service_quantity,
	sku_service_unit_price,
	sku_service_price
FROM
	aws_oci_output.processed_records_oct pro
WHERE resource_group='medialive'
	AND line_item_usage_account_id in (select LinkedAccountID from aws_oci_output.ParamountExtId2Pluto)
"""



# Function to connect to ClickHouse and execute a query
def query_clickhouse(ip_address, port, username, password, query, output_file):
    # Create a connection to the ClickHouse database
    client = clickhouse_connect.get_client(host=ip_address, port=port, username=username, password=password)
    
    # Execute the query
    result = client.query(query)
    
    # Fetch the column names and rows
    columns = result.column_names
    rows = result.result_rows
    
    # Write the result to a CSV file
    with open(output_file, 'w', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)
        csvwriter.writerow(columns)  # Write the column names
        csvwriter.writerows(rows)    # Write the rows

    print(f"Query results have been exported to {output_file}")
# Example usage
ip_address = '18.219.204.42'
port = 8123  # Replace with your port number
username = 'test'
password = 'test'
query = Query
output_file = 'test\ParamountDataExports\ParamountExtId2Pluto.csv'
# output_file = 'test\ParamountDataExports\ParamountExtId1CBS.csv'
# output_file = 'test\ParamountDataExports\ParamountTechAccounts.csv'
# output_file = 'test\ParamountDataExports\ParamountMissingAccounts.csv'

query_clickhouse(ip_address, port, username, password, query, output_file)